### ISSUE TITLE
If Username Doesn't Exist

### ISSUE THREAD

**Issue by decodemicah** [joshxfi/github-stats-generator#1]
The screenshots below show what it looks like when a *username or account doesn't exist*. I think it's better if it has a message like **Username Not Found**.<br>
![image](https://user-images.githubusercontent.com/88300426/131141701-8003693b-dd0a-4439-9f6f-a9d5039e4a1c.png)
![image](https://user-images.githubusercontent.com/88300426/131141985-9bfd3590-0bd3-4c45-8d1c-dc15408b556f.png)

**Comment by joshxfi** [comment]
The `GitHub Streak` has a different error message because it comes from a different repo. I actually made a custom error message for this, it's found on this commit &rarr; 6aa7b1aa85456668c26c576b3ae198d1769aa189 It worked perfectly fine on `development` but there was some problem on `production` which led me to removing it for the meantime &rarr; 27cde99777d034eae1e3f356f2fde05e4287d8a8

**Comment by decodemicah** [comment]
I already see that. By the way, thanks for this.
